---
- name: Reset Debian Network Configuration
  hosts: classcomputers
  become: yes
  tasks:
    - name: Stop networking service
      systemd:
        name: networking
        state: stopped
      ignore_errors: yes

    - name: Disable networking service
      systemd:
        name: networking
        enabled: no
      ignore_errors: yes

    - name: Enable NetworkManager
      systemd:
        name: NetworkManager
        enabled: yes

    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted

    - name: Remove network interfaces configuration
      file:
        path: /etc/network/interfaces*
        state: absent

    - name: Reset resolv.conf
      shell: |
        echo "Reseteando resolv.conf..."
        cat > /etc/resolv.conf <<EOF
        nameserver 1.1.1.1
        nameserver 1.0.0.1
        EOF